<?php
/**
 * Server-rendered markup for the Lead Story block.
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Saved content, intentionally empty.
 * @var WP_Block $block      Block instance.
 *
 * @package FieldnoteEditorialBlocks
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$post_id = isset( $attributes['postId'] ) ? absint( $attributes['postId'] ) : 0;
$story   = $post_id ? get_post( $post_id ) : null;

if ( ! $story || 'post' !== $story->post_type || 'publish' !== $story->post_status ) {
	$latest = get_posts(
		array(
			'numberposts' => 1,
			'post_status' => 'publish',
			'post_type'   => 'post',
		)
	);
	$story  = $latest ? $latest[0] : null;
}

if ( ! $story ) {
	return;
}

$layout         = isset( $attributes['layout'] ) && in_array( $attributes['layout'], array( 'split', 'stacked' ), true ) ? $attributes['layout'] : 'split';
$image_position = isset( $attributes['imagePosition'] ) && 'right' === $attributes['imagePosition'] ? 'right' : 'left';
$show_category  = ! isset( $attributes['showCategory'] ) || (bool) $attributes['showCategory'];
$show_excerpt   = ! isset( $attributes['showExcerpt'] ) || (bool) $attributes['showExcerpt'];
$eyebrow        = isset( $attributes['eyebrow'] ) ? $attributes['eyebrow'] : __( 'Featured dispatch', 'fieldnote-editorial-blocks' );
$categories     = get_the_category( $story->ID );
$category       = $categories ? $categories[0] : null;
$excerpt        = get_the_excerpt( $story );
$image          = get_the_post_thumbnail(
	$story->ID,
	'large',
	array(
		'class'    => 'fieldnote-lead-story__image',
		'decoding' => 'async',
	)
);
$classes        = sprintf( 'fieldnote-lead-story is-layout-%1$s is-image-%2$s', $layout, $image_position );
$media_label    = sprintf(
	/* translators: %s: post title. */
	__( 'Read %s', 'fieldnote-editorial-blocks' ),
	get_the_title( $story )
);
?>
<article <?php echo get_block_wrapper_attributes( array( 'class' => $classes ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>>
	<a class="fieldnote-lead-story__media" href="<?php echo esc_url( get_permalink( $story ) ); ?>" aria-label="<?php echo esc_attr( $media_label ); ?>">
		<?php if ( $image ) : ?>
			<?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by core. ?>
		<?php else : ?>
			<span class="fieldnote-lead-story__placeholder"><span>FN</span></span>
		<?php endif; ?>
	</a>

	<div class="fieldnote-lead-story__content">
		<p class="fieldnote-lead-story__eyebrow"><?php echo esc_html( $eyebrow ); ?></p>
		<?php if ( $show_category && $category ) : ?>
			<a class="fieldnote-lead-story__category" href="<?php echo esc_url( get_category_link( $category ) ); ?>"><?php echo esc_html( $category->name ); ?></a>
		<?php endif; ?>

		<h2 class="fieldnote-lead-story__title"><a href="<?php echo esc_url( get_permalink( $story ) ); ?>"><?php echo esc_html( get_the_title( $story ) ); ?></a></h2>

		<?php if ( $show_excerpt && $excerpt ) : ?>
			<p class="fieldnote-lead-story__excerpt"><?php echo esc_html( wp_trim_words( $excerpt, 34 ) ); ?></p>
		<?php endif; ?>

		<div class="fieldnote-lead-story__meta">
			<span><?php echo esc_html( get_the_author_meta( 'display_name', $story->post_author ) ); ?></span>
			<time datetime="<?php echo esc_attr( get_the_date( DATE_W3C, $story ) ); ?>"><?php echo esc_html( get_the_date( '', $story ) ); ?></time>
		</div>
	</div>
</article>
